
[AtCoder]
  ContestID = "abc007"
  ContestURL = "https://atcoder.jp/contests/abc007"
  TaskID = "abc007_3"
  TaskName = "C - 幅優先探索"
  TaskURL = "https://atcoder.jp/contests/abc007/tasks/abc007_3"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
