
[AtCoder]
  ContestID = "abc013"
  ContestURL = "https://atcoder.jp/contests/abc013"
  TaskID = "abc013_2"
  TaskName = "B - éŒ "
  TaskURL = "https://atcoder.jp/contests/abc013/tasks/abc013_2"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
