
[AtCoder]
  ContestID = "abc098"
  ContestURL = "https://atcoder.jp/contests/abc098"
  TaskID = "arc098_a"
  TaskName = "C - Attention"
  TaskURL = "https://atcoder.jp/contests/abc098/tasks/arc098_a"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
