
[AtCoder]
  ContestID = "abc011"
  ContestURL = "https://atcoder.jp/contests/abc011"
  TaskID = "abc011_1"
  TaskName = "A - 来月は何月？"
  TaskURL = "https://atcoder.jp/contests/abc011/tasks/abc011_1"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
