
[AtCoder]
  ContestID = "abc052"
  ContestURL = "https://atcoder.jp/contests/abc052"
  TaskID = "arc067_a"
  TaskName = "C - Factors of Factorial"
  TaskURL = "https://atcoder.jp/contests/abc052/tasks/arc067_a"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
