
[AtCoder]
  ContestID = "abc057"
  ContestURL = "https://atcoder.jp/contests/abc057"
  TaskID = "abc057_c"
  TaskName = "C - Digits in Multiplication"
  TaskURL = "https://atcoder.jp/contests/abc057/tasks/abc057_c"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
