
[AtCoder]
  ContestID = "abc106"
  ContestURL = "https://atcoder.jp/contests/abc106"
  TaskID = "abc106_b"
  TaskName = "B - 105"
  TaskURL = "https://atcoder.jp/contests/abc106/tasks/abc106_b"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
