
[AtCoder]
  ContestID = "pakencamp-2019-day3"
  ContestURL = "https://atcoder.jp/contests/pakencamp-2019-day3"
  TaskID = "pakencamp_2019_day3_d"
  TaskName = "D - パ研軍旗"
  TaskURL = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
