
[AtCoder]
  ContestID = "abc166"
  ContestURL = "https://atcoder.jp/contests/abc166"
  TaskID = "abc166_f"
  TaskName = "F - Three Variables Game"
  TaskURL = "https://atcoder.jp/contests/abc166/tasks/abc166_f"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
