
[AtCoder]
  ContestID = "abc016"
  ContestURL = "https://atcoder.jp/contests/abc016"
  TaskID = "abc016_4"
  TaskName = "D - 一刀両断"
  TaskURL = "https://atcoder.jp/contests/abc016/tasks/abc016_4"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
