
[AtCoder]
  ContestID = "abc084"
  ContestURL = "https://atcoder.jp/contests/abc084"
  TaskID = "abc084_c"
  TaskName = "C - Special Trains"
  TaskURL = "https://atcoder.jp/contests/abc084/tasks/abc084_c"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
