
[AtCoder]
  ContestID = "abc031"
  ContestURL = "https://atcoder.jp/contests/abc031"
  TaskID = "abc031_c"
  TaskName = "C - 数列ゲーム"
  TaskURL = "https://atcoder.jp/contests/abc031/tasks/abc031_c"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
