
[AtCoder]
  ContestID = "abc157"
  ContestURL = "https://atcoder.jp/contests/abc157"
  TaskID = "abc157_c"
  TaskName = "C - Guess The Number"
  TaskURL = "https://atcoder.jp/contests/abc157/tasks/abc157_c"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
