
[AtCoder]
  ContestID = "abc148"
  ContestURL = "https://atcoder.jp/contests/abc148"
  TaskID = "abc148_d"
  TaskName = "D - Brick Break"
  TaskURL = "https://atcoder.jp/contests/abc148/tasks/abc148_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
