
[AtCoder]
  ContestID = "abc165"
  ContestURL = "https://atcoder.jp/contests/abc165"
  TaskID = "abc165_f"
  TaskName = "F - LIS on Tree"
  TaskURL = "https://atcoder.jp/contests/abc165/tasks/abc165_f"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
