
[AtCoder]
  ContestID = "abc099"
  ContestURL = "https://atcoder.jp/contests/abc099"
  TaskID = "abc099_c"
  TaskName = "C - Strange Bank"
  TaskURL = "https://atcoder.jp/contests/abc099/tasks/abc099_c"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
