
[AtCoder]
  ContestID = "abc095"
  ContestURL = "https://atcoder.jp/contests/abc095"
  TaskID = "arc096_b"
  TaskName = "D - Static Sushi"
  TaskURL = "https://atcoder.jp/contests/abc095/tasks/arc096_b"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.6"
  Key = "go"
  Language = "Go (1.6)"
  LanguageCode = "3013"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
