
[AtCoder]
  ContestID = "abc021"
  ContestURL = "https://atcoder.jp/contests/abc021"
  TaskID = "abc021_d"
  TaskName = "D - 多重ループ"
  TaskURL = "https://atcoder.jp/contests/abc021/tasks/abc021_d"

[Environment]
  BuildCmd = "go build -o ./a.out main.go"
  BuildCmdOnDocker = "go build -o a.out main.go"
  CleanCmd = "rm ./a.out"
  Cmd = "./a.out"
  CmdOnDocker = "./a.out"
  DockerImage = "docker.io/library/golang:1.14.1"
  Key = "go"
  Language = "Go (1.14.1)"
  LanguageCode = "4026"
  Note = ""
  SrcName = "main.go"
  Template = "internal/go/main.go"
